-- Enable RLS on all Phase 2+ tables (no policies = API REST blocked with public key)

ALTER TABLE "Room" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Species" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Plant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CareEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Photo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Diagnosis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiUsage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DigestLog" ENABLE ROW LEVEL SECURITY;

-- Phase 7 tables
ALTER TABLE "Sensor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SensorReading" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AlertLog" ENABLE ROW LEVEL SECURITY;
